---
# file: roles/pacemaker/tasks/main.yml
- include: destroy.yml
  when: pacemaker_destroy_cluster and pacemaker_destroy_cluster == true

- include: install.yml
- include: user.yml
- pause:
    prompt="Waiting few seconds..."
    seconds=5
- include: auth.yml
- include: sync.yml
- include: start.yml

- include: firewall.yml
  when: pacemaker_firewalld and pacemaker_firewalld == true

- include: properties.yml
