---
# file: roles/pacemaker/tasks/sync.yml
- name: Syncing corosync.conf on each cluster nodes
  pcs_cluster:
    command=sync
  when: inventory_hostname == master
  tags:
    - pacemaker
    - pacemaker-sync
